services:
  opensearch:
    image: opensearchproject/opensearch:2.16.0
    container_name: opensearch-node
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
    ports:
      - "9200:9200"
    networks:
      - log-net

  backend:
    build: ./backend
    container_name: log-backend
    ports:
      - "8081:8080"
      - "1514:1514/udp"
    environment:
      - OPENSEARCH_NODE=http://opensearch:9200
    depends_on:
      - opensearch
    networks:
      - log-net

  frontend:
    build: ./frontend
    container_name: log-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - log-net

networks:
  log-net:
    driver: bridge
